version: '3.1'


services:

  postgres-dev:
    image: postgres:11.1
    restart: always
    volumes: 
      - postgres-dev:/var/lib/postgresql
    ports:
      - '5432:5432'
    secrets:
      - psql_user
      - psql_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_password
      POSTGRES_USER_FILE: /run/secrets/psql_user

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin-dev:/var/lib/pgadmin
      - ./docker/servers.json:/servers.json
      - ./sql:/var/lib/pgadmin/storage/user/
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

secrets:
  psql_user:
    file: ./docker/psql_user.txt
  psql_password:
    file: ./docker/psql_password.txt


volumes:
  postgres-dev:
  tomcat-dev:
  pgadmin-dev:
