version: '3.1'


services:

  postgres-dev:
    image: postgres:11.1
    restart: always
    volumes: 
      - postgres-dev:/var/lib/postgresql
    ports:
      - '5432:5432'
    secrets:
      - psql_user
      - psql_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_password
      POSTGRES_USER_FILE: /run/secrets/psql_user

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

secrets:
  psql_user:
    file: ./docker/psql_user.txt
  psql_password:
    file: ./docker/psql_password.txt


volumes:
  postgres-dev:
  tomcat-dev:
